### PR TITLE
Tune Up Linguist

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by codekitchen** [comment]
Can you give me more information on what this accomplishes? I'm not familiar with anything called linguist, let alone why you'd need to tune it up.

**Comment by sergeyklay** [comment]
Oh, okay.
Let me show

linguist

linguist-2

**Comment by codekitchen** [comment]
Ah I see, i googled "linguist" and that wasn't any help but "github linguist" takes me to the explanation on https://github.com/github/linguist#using-gitattributes

Not all of that css code is vendored, but most of it is, so 👍

thanks!

**Comment by sergeyklay** [comment]
You're welcome 👍

**Pull request merged**
