### PR TITLE
[TASK] Update go and usw alpine

### PR DESCRIPTION
**Pull request by beardcoder**

### CODE REVIEW

**Comment by codekitchen** [comment]
Thanks for the updates. Does switching to the alpine version of nginx-proxy give us full HTTP/2 support even though we're using our own template file? Or did you have a different motivation for doing the switch.

**Comment by beardcoder** [comment]
The alpine version have 2 benefits. The size and the http2 support.

**Comment by codekitchen** [comment]
Cool yeah, having http2 support sounds worthwhile, I guess that requires the alpine image for now because of the newer openssl version. I'll have to do a little more testing which might take me a few days.

**Comment by codekitchen** [comment]
I'm assuming you made the switch to just copying `join-networks` from the local dir for easier local builds, but that'd break the automated Docker Hub build since that binary file isn't committed to git. There's no support on Docker Hub for running a build script, it only builds the Dockerfile itself. So I can't accept those changes.

I'm not particularly married to the way it works now, that was just a quick & easy solution at the time, but we would need to come up with something else that works with Docker Hub.

**Comment by codekitchen** [comment]
These features have been merged as part of #51 , thanks

**Pull request closed without merging**
